config/routes.rb
Rails.application.routes.draw do


  delete "tasks/:id", to: "tasks#destroy", as: :delete_task
  get "tasks/:id/edit", to: "tasks#edit", as: :edit_task #editatask
  patch "tasks/:id", to: "tasks#update"
  get "tasks/new", to: "tasks#new"  #making a new task
  post "tasks", to: "tasks#create"
  get "tasks", to: "tasks#index"
  get "tasks/:id", to: "tasks#show", as: :task


end


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # add two routes to handle the creation of a task
  # one route is to display the task form
  #the other route is to handle the POST request generated when submitting the form

  # add two routes for update
  # need to be able to edit a task--changing its title, its details and marking it as completed

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    task = Task.new(task_params)
    task.save
    redirect_to tasks_path
  end

  def task_params
    params.require(:task).permit(:title, :details)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end



end


# need to get the html form for editing = 1 request
# need to patch the parameters to update an existing task= 1 request

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_for(@task) do |f| %>
<%= f.label :title, class: 'form-label'  %>
<%= f.text_field :title, class: 'form-control' %>
<%= f.label :details, class: 'form-label' %>
<%= f.text_field :details, class: 'form-control' %>
<%= f.label :completed, class: 'form-check-label' %>
<%= f.check_box :completed, class: 'form-check-control'%>
<%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/tasks/index.html.erb
<h1>All Tasks</h1>

<%= link_to "Create a new task", tasks_new_path(@task) %>

<% @tasks.each do |task| %>
<li><a href="/tasks/<%=task.id%>"><%= task.title %></a></li>
<% end %>









<%# now we have a list of tasks, we need to
click on the task title and navigate to a new page,
displaying the details of this task
add a new route, a new controller action and
a new view
this action should find a specific task-thanks to its id
directly from the params

---use the link_to rails helper%>

app/views/tasks/new.html.erb
<h1>Create a new Task</h1>

<%= form_for(@task) do |f| %>
<%= f.label :title, class: 'form-label'  %>
<%= f.text_field :title, class: 'form-control' %>
<%= f.label :details, class: 'form-label' %>
<%= f.text_field :details, class: 'form-control' %>
<%= f.label :completed, class: 'form-check-label' %>
<%= f.check_box :completed, class: 'form-check-control'%>
<%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/tasks/show.html.erb
<h1>your task: </h1>

<%= @task.details %>

<%= link_to  "Update Task", edit_task_path(@task.id) %>

<%= link_to  "Delete", delete_task_path(@task), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}  %>